version: '3.8'

services:
  cliente-service:
    build: ./cliente-service
    ports:
      - "8081:8080"
    networks:
      - app-network

  # pedido-service:
  #   build: ./pedido-service
  #   ports:
  #     - "8082:8080"
  #   networks:
  #     - app-network

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
